name: CI build to verify quality
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  verify-quality:
    name: Verify quality
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      checks: write
      pull-requests: write
      contents: read
      issues: read
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - name: Setup .NET 10 SDK
        id: setup-dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
      - name: Verify quality
        run: dotnet test --solution Eshva.Testing.Reqnroll.slnx --configuration Release --report-xunit --report-xunit-filename test_result.xml --results-directory .
        working-directory: code
      - name: Publish test results
        if: (!cancelled())
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: './**/test_result.xml'
          check_name: 'Test results'
          action_fail: true
  code-coverage:
    name: Calculate code coverage and metrics
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      checks: write
      pull-requests: write
      contents: read
      issues: read
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - name: Setup .NET 10 SDK
        id: setup-dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
      - name: Setup dotnet-coverage tool
        run: dotnet tool install --global dotnet-coverage
      - name: Calculate code coverage and metrics
        run: dotnet-coverage collect "dotnet test --solution Eshva.Testing.Reqnroll.slnx" --output-format cobertura --output cobertura.xml
        working-directory: code
      - name: Restore coverage history
        if: (!cancelled())
        uses: dawidd6/action-download-artifact@v11
        with:
          name: coverage-history-ci
          path: coverage-history-ci
        continue-on-error: true
      - name: Generate code coverage and metrics report
        if: (!cancelled())
        uses: danielpalme/ReportGenerator-GitHub-Action@5.5.0
        with:
          reports: code/cobertura.xml
          targetdir: coverage-ci
          reporttypes: MarkdownSummaryGithub;MarkdownDeltaSummary;Badges
          historydir: coverage-history-ci
          assemblyfilters: +Eshva.Testing.Reqnroll
          classfilters: -*Settings
      - name: Upload coverage report
        if: (!cancelled())
        uses: actions/upload-artifact@v5
        with:
          name: coverage-ci
          path: coverage-ci
      - name: Upload coverage history
        if: (!cancelled())
        uses: actions/upload-artifact@v5
        with:
          name: coverage-history-ci
          path: coverage-history-ci
      - name: Write code coverage summary to Job Summary
        if: (!cancelled())
        run: cat coverage-ci/SummaryGithub.md >> $GITHUB_STEP_SUMMARY
      - name: Write code coverage delta to Job Summary
        if: (!cancelled())
        run: cat coverage-ci/DeltaSummary.md >> $GITHUB_STEP_SUMMARY
        continue-on-error: true
      - name: Add code coverage summary to PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request' && (!cancelled())
        with:
          recreate: true
          path: coverage-ci/SummaryGithub.md
      - name: Add code coverage delta to PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request' && (!cancelled())
        with:
          recreate: true
          path: coverage-ci/DeltaSummary.md
        continue-on-error: true
