name: Build the NuGet-package and publish it to nuget.org
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  verify-quality:
    name: Verify quality
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      checks: write
      pull-requests: write
      contents: read
      issues: read
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - name: Setup .NET 10 SDK
        id: setup-dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
      - name: Verify quality
        run: dotnet test --solution Eshva.Testing.Reqnroll.slnx --report-xunit --report-xunit-filename test_result.xml --results-directory .
        working-directory: ./code
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: "./**/test_result.xml"
          check_name: "Test results"
          action_fail: true
  build-and-publish:
    name: Build the NuGet-package and publish it to nuget.org
    needs: [ verify-quality ]
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - name: Verify commit exists in origin/master
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/master
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Build sources
        run: dotnet build code/solutions/Eshva.Testing.Reqnroll/Eshva.Testing.Reqnroll.csproj --configuration Release
      - name: Pack the NuGet-package
        run: dotnet pack code/solutions/Eshva.Testing.Reqnroll/Eshva.Testing.Reqnroll.csproj --configuration Release /p:Version=${VERSION} --no-build --output .
      - name: NuGet login (OIDC â†’ temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}
      - name: Publish the NuGet-package to nuget.org
        run: dotnet nuget push Eshva.Testing.Reqnroll.${VERSION}.nupkg --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
  code-coverage:
    name: Calculate code coverage and metrics
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      checks: write
      pull-requests: write
      contents: read
      issues: read
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - name: Setup .NET 10 SDK
        id: setup-dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
      - name: Setup dotnet-coverage tool
        run: dotnet tool install --global dotnet-coverage
      - name: Calculate code coverage and metrics
        run: dotnet-coverage collect "dotnet test --solution Eshva.Testing.Reqnroll.slnx" --output-format cobertura --output cobertura.xml
        working-directory: code
      - name: Restore coverage history
        if: (!cancelled())
        uses: dawidd6/action-download-artifact@v11
        with:
          name: coverage-history-release
          path: coverage-history-release
        continue-on-error: true
      - name: Generate code coverage and metrics report
        if: (!cancelled())
        uses: danielpalme/ReportGenerator-GitHub-Action@5.5.0
        with:
          reports: code/cobertura.xml
          targetdir: coverage-release
          reporttypes: MarkdownSummaryGithub;MarkdownDeltaSummary;Badges
          historydir: coverage-history-release
          assemblyfilters: +Eshva.Testing.Reqnroll
          classfilters: -*Settings
      - name: Upload coverage report
        if: (!cancelled())
        uses: actions/upload-artifact@v5
        with:
          name: coverage-release
          path: coverage-release
      - name: Upload coverage history
        if: (!cancelled())
        uses: actions/upload-artifact@v5
        with:
          name: coverage-history-release
          path: coverage-history-release
      - name: Write code coverage summary to Job Summary
        if: (!cancelled())
        run: cat coverage-release/SummaryGithub.md >> $GITHUB_STEP_SUMMARY
      - name: Write code coverage delta to Job Summary
        if: (!cancelled())
        run: cat coverage-release/DeltaSummary.md >> $GITHUB_STEP_SUMMARY
        continue-on-error: true
      - name: Add code coverage summary to PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request' && (!cancelled())
        with:
          recreate: true
          path: coverage-release/SummaryGithub.md
      - name: Add code coverage delta to PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request' && (!cancelled())
        with:
          recreate: true
          path: coverage-release/DeltaSummary.md
        continue-on-error: true
